export const huiFamily = [
  {
    name: "Betty Hui (Shen)",
    DOB: "01/17/X",
    parent: ["Andrew Shen", "Lydia Shen"],
    offspring: [
      "Samuel Hui",
      "Benjamin Hui",
      "Faith Hui",
      "Bethany Hui",
      "Pearl Hui",
      "Ruth (Cici) Hui",
    ],
    siblingID: "X",
    family: "a",
  },
  {
    name: "San Hui",
    DOB: "03/28/69",
    parent: ["X", "X"],
    offspring: [
      "Samuel Hui",
      "Benjamin Hui",
      "Faith Hui",
      "Bethany Hui",
      "Pearl Hui",
      "Ruth (Cici) Hui",
    ],
    siblingID: "X",
    family: "a",
  },
  {
    name: "Samuel Hui",
    DOB: "04/12/1994",
    parent: ["San Hui", "Betty Hui (Shen)"],
    offspring: [],
    siblingID: "1",
    family: "a",
  },
  {
    name: "Benjamin Hui",
    DOB: "8/03/1998",
    parent: ["San Hui", "Betty Hui (Shen)"],
    offspring: [],
    siblingID: "2",
    family: "a",
  },
  {
    name: "Faith Hui",
    DOB: "05/07/2003",
    parent: ["San Hui", "Betty Hui (Shen)"],
    offspring: [],
    siblingID: "3",
    family: "a",
  },
  {
    name: "Bethany Hui",
    DOB: "08/26/2008",
    parent: ["San Hui", "Betty Hui (Shen)"],
    offspring: [],
    siblingID: "4",
    family: "a",
  },
  {
    name: "Pearl Hui",
    DOB: "01/18/2010",
    parent: ["San Hui", "Betty Hui (Shen)"],
    offspring: [],
    siblingID: "5",
    family: "a",
  },
  {
    name: "Ruth (Cici) Hui",
    DOB: "08/06/2011",
    parent: ["San Hui", "Betty Hui (Shen)"],
    offspring: [],
    siblingID: "6",
    family: "a",
  },

  {
    name: "Pak Hui (Wu)",
    DOB: "XX/XX/XX",
    parent: ["X", "X"],
    offspring: ["Vincent Hui", "Callum Hui"],
    siblingID: "X",
    family: "b",
  },
  {
    name: "Dominic Hui",
    DOB: "XX/XX/XX",
    parent: ["X", "X"],
    offspring: ["Vincent Hui", "Callum Hui"],
    siblingID: "X",
    family: "b",
  },
  {
    name: "Vincent Hui",
    DOB: "06/15/1992",
    parent: ["Dominic Hui", "Pak Hui (Wu)"],
    offspring: [],
    siblingID: "1",
    family: "b",
  },
  {
    name: "Callum Hui",
    DOB: "12/22/1999",
    parent: ["Dominic Hui", "Pak Hui (Wu)"],
    offspring: [],
    siblingID: "2",
    family: "b",
  },
];

export const firstborn = huiFamily.filter((member) => member.siblingID === "1");
